version: '3'
#networks:
#  default:
#    name: dev
services:
  nifi:
   #docker run -d --name mynifidemo -p 8080:8080 apache/nifi
    image: apache/nifi
    container_name: mynifi1
    ports:
      # http://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#port-configuration
      - "8080:8080/tcp" # HTTP interface
      - "9443:9443/tcp" # HTTPS interface
    volumes:
      - /C/Docker/SolrNiFi/NiFi/certs:/opt/certs
      - /C/Docker/SolrNiFi/NiFi/drivers:/opt/nifi/nifi-current/drivers
      - /C/Docker/SolrNiFi/NiFi/logs:/opt/nifi/nifi-current/logs
      - /C/Docker/SolrNiFi/NiFi/mylogs:/opt/nifi/nifi-current/mylogs
  solr:
    #docker run -d --name mysolrdemo -p 8983:8983 my-image solr-precreate mycore /opt/solr/server/solr/configsets/myconfig
    image: my-solr-image
    container_name: mysolr1
    ports:
      - "8983:8983"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core mycore; precreate-core banana-int; exec solr -f"
      #- "precreate-core mycore /opt/solr/server/solr/configsets/myconfig; precreate-core banana-int; exec solr -f"
    volumes:
      - /C/Docker/SolrNiFi/solr/configsets:/opt/solr/server/solr/configsets
    #command: solr-precreate mycore /opt/solr/server/solr/configsets/myconfig; /opt/docker-solr/scripts/solr-precreate banana-int /opt/solr/server/solr/configsets/_default
    # ; solr-precreate banana-int"
